### ISSUE TITLE
reactor相关请教

### ISSUE THREAD

**Issue by curtiseng** [tony612/tokio-internals#2]
> 另一个是，多个 worker 线程会并发地执行 tasks，但只有一个 worker 线程会作为 reactor 来 poll events，新的 events 可能是由 reactor 自己，也可能是由其他 worker 线程来执行对应的 future。

文中这样描述，是否和 https://github.com/tokio-rs/tokio/pull/660 这个pr冲突。

**Comment by tony612** [comment]
后来在[这个 PR](https://github.com/tokio-rs/tokio/pull/1807) 改了一下，现在之后一个 reactor 了。可以看[这里](https://tony612.github.io/tokio-internals/02_worker_thread_1.html#%E7%AD%89%E5%BE%85-events)
> 当我们有多个 worker threads 时，只有一个 worker 会抢到 runtime::driver::Driver 的“锁”(没抢到的并不会挂起而是返回 None 而执行 else)而执行 park_driver，其他 worker 会 park_condvar，后边会看到 park_driver 其实就是 poll events，因此只有一个 worker 线程会成为 reactor
